(define (batch-convert-png-to-jpg in-dir out-dir)
  (let* (
    (filelist (cadr (file-glob in-dir "*.png" 1)))
    (image 0)
    (drawable 0)
    (filename "")
    )
    (while (pair? filelist)
      (set! filename (car filelist))
      (set! image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
      (set! drawable (car (gimp-image-get-active-layer image)))
      (let ((newfilename (string-append out-dir "/" (substring filename 0 (- (string-length filename) 4)) ".jpg")))
        (file-jpeg-save RUN-NONINTERACTIVE image drawable newfilename newfilename 1.0 0 1 0 "" 0 1 0 0)
      )
      (set! filelist (cdr filelist))
    )
    (gimp-quit 0)
  )
)

(batch-convert-png-to-jpg "." ".")

